development:
  adapter: postgresql
  encoding: unicode
  database: myapp_dev
  host: localhost
  pool: 5
  username: rey810
  password: Carpediem321.

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  host: localhost
  pool: 5
  username: rey810
  password: Carpediem321.
